import {ConnectedPosition} from '@angular/cdk/overlay';
import {EvoTooltipPosition} from '../enums/evo-tooltip-position';

export const EVO_CONNECTED_POSITION = (offset: number): {[key in EvoTooltipPosition]: ConnectedPosition} => ({
    [EvoTooltipPosition.TOP]: {
        originX: 'center',
        originY: 'top',
        overlayX: 'center',
        overlayY: 'bottom',
        offsetY: -offset,
        panelClass: EvoTooltipPosition.TOP,
    },
    [EvoTooltipPosition.BOTTOM]: {
        originX: 'center',
        originY: 'bottom',
        overlayX: 'center',
        overlayY: 'top',
        offsetY: offset,
        panelClass: EvoTooltipPosition.BOTTOM,
    },
    [EvoTooltipPosition.LEFT]: {
        originX: 'start',
        originY: 'center',
        overlayX: 'end',
        overlayY: 'center',
        offsetX: -offset,
        panelClass: EvoTooltipPosition.LEFT,
    },
    [EvoTooltipPosition.RIGHT]: {
        originX: 'end',
        originY: 'center',
        overlayX: 'start',
        overlayY: 'center',
        offsetX: offset,
        panelClass: EvoTooltipPosition.RIGHT,
    },
    [EvoTooltipPosition.TOP_START]: {
        originX: 'start',
        originY: 'top',
        overlayX: 'start',
        overlayY: 'bottom',
        offsetY: -offset,
        panelClass: EvoTooltipPosition.TOP_START,
    },
    [EvoTooltipPosition.TOP_END]: {
        originX: 'end',
        originY: 'top',
        overlayX: 'end',
        overlayY: 'bottom',
        offsetY: -offset,
        panelClass: EvoTooltipPosition.TOP_END,
    },
    [EvoTooltipPosition.RIGHT_START]: {
        originX: 'end',
        originY: 'top',
        overlayX: 'start',
        overlayY: 'top',
        offsetX: offset,
        panelClass: EvoTooltipPosition.RIGHT_START,
    },
    [EvoTooltipPosition.RIGHT_END]: {
        originX: 'end',
        originY: 'bottom',
        overlayX: 'start',
        overlayY: 'bottom',
        offsetX: offset,
        panelClass: EvoTooltipPosition.RIGHT_END,
    },
    [EvoTooltipPosition.BOTTOM_END]: {
        originX: 'end',
        originY: 'bottom',
        overlayX: 'end',
        overlayY: 'top',
        offsetY: offset,
        panelClass: EvoTooltipPosition.BOTTOM_END,
    },
    [EvoTooltipPosition.BOTTOM_START]: {
        originX: 'start',
        originY: 'bottom',
        overlayX: 'start',
        overlayY: 'top',
        offsetY: offset,
        panelClass: EvoTooltipPosition.BOTTOM_START,
    },
    [EvoTooltipPosition.LEFT_END]: {
        originX: 'start',
        originY: 'bottom',
        overlayX: 'end',
        overlayY: 'bottom',
        offsetX: -offset,
        panelClass: EvoTooltipPosition.LEFT_END,
    },
    [EvoTooltipPosition.LEFT_START]: {
        originX: 'start',
        originY: 'top',
        overlayX: 'end',
        overlayY: 'top',
        offsetX: -offset,
        panelClass: EvoTooltipPosition.LEFT_START,
    },
});
