import { EVO_TOOLTIP_POSITION } from '../enums/evo-tooltip-position';

export const EVO_DEFAULT_POSITIONS_ORDER: EVO_TOOLTIP_POSITION[] = [
    EVO_TOOLTIP_POSITION.TOP,
    EVO_TOOLTIP_POSITION.TOP_END,
    EVO_TOOLTIP_POSITION.RIGHT_START,
    EVO_TOOLTIP_POSITION.RIGHT,
    EVO_TOOLTIP_POSITION.RIGHT_END,
    EVO_TOOLTIP_POSITION.BOTTOM_END,
    EVO_TOOLTIP_POSITION.BOTTOM,
    EVO_TOOLTIP_POSITION.BOTTOM_START,
    EVO_TOOLTIP_POSITION.LEFT_END,
    EVO_TOOLTIP_POSITION.LEFT,
    EVO_TOOLTIP_POSITION.LEFT_START,
    EVO_TOOLTIP_POSITION.TOP_START,
];
